//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Food_Ingredient_Analyzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyOrderByFrequency
    {
        public string CurrencyCode { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string FullCurrencyName { get; set; }
    }
}
