//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Food_Ingredient_Analyzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public string FoodName { get; set; }
        public Nullable<int> ForLifeStage { get; set; }
        public string Ingredients { get; set; }
        public Nullable<decimal> Mass { get; set; }
        public Nullable<int> UnitOfMass { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CurrencyOfPrice { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
