//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Food_Ingredient_Analyzer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public string Quote { get; set; }
        public decimal ExchangeRate { get; set; }
        public System.DateTime ExpiryDateTime { get; set; }
    }
}
